### ISSUE TITLE
Courses to initiate 

### ISSUE THREAD

**Issue by accakks** [CodeDocsJECRC/community-committee#14]
Lets list some courses that we can initiate this semester.
These can be:

- **Courses** : The ones that require student enrollment. Lectures > 2
- **Extra topics/sessions**: Independent. Required lectures <2. Enrollment would subject to respective topic.
For example, `Introduction to Git` may require only enrolled students. But an `Informative session on GSoC`  won't.

**Comment by maddhruv** [comment]
A proposed list of courses we already had prepared -
### courses
- Intro to Git and GitHub - so that the future lectures and sessions can be completed with ease for assignments and rollouts
- Introduction to Web and Android - are most fascinating, covers half of the industry, easy to learn at a beginner stage, tutors know the stuff well and good.
- Introduction to devOps and cloud part - easy to deploy services, databases etc
- iOT and embedded part for robotics and such people

### sessions, topics, meetups
- linux sessions involve - shell, networking, ssh(engineering part)
- open source tools - flow, mocha, webpack, bootstrap, jQuery
- new techs in the river - kotlin, cloud tools etc
- meetups - js, python, android

**Comment by accakks** [comment]
Let's finalise on courses and content @maddhruv  @amritsrivastava alongwith details & timeline , so that we can start looking for mentors for each. #19 
And they get time to prepare.
We'll also need to talk to college authorities in July itself.

**Comment by maddhruv** [comment]
@accakks submit a PR named CD201.md
And that shall be the course for this session

**Comment by aditya98ak** [comment]
@maddhruv @accakks @amritsrivastava
What about these?
Django, Building API's using django-rest-framework
And python for data science ( data analysis, visualization via numpy, pandas, matplotlib, seaborn, plotly etc)
And basic introduction to ML models via scikit-learn and their intuition?

**Comment by amritsrivastava** [comment]
@aditya98ak we are planning to include these topics too, you will soon get notified about these.

**Comment by aditya98ak** [comment]
@amritsrivastava Cool, will be waiting for it!

**Comment by accakks** [comment]
@aditya98ak Can you propose 7-9 lecture plan for your proposed course. Include basics of Python

**Comment by aditya98ak** [comment]
@accakks  I can propose a course 'Fast Track to Python' that will be sufficient to explore python-frameworks. 
Is that fair enough?
and after fast track to python. We can pivot to Django or data-science.
What say? @maddhruv @accakks @amritsrivastava

**Comment by accakks** [comment]
What I was talking about is maybe just one 1-1.5 hour lecture for Python introduction. You'll just have to introduce basics. 

A separate course might not be necessary. 

You can check out design of web course on CD101. 

It can be 8-9 lectures. 

See after classes, there would be resources for self study, and assignment to learn what class was all about. There'd be 2 classes per week only. 

I don't think Python needs a whole new course. 

If you're focused more on data science etc you can maybe propose Python frameworks as an additional session.

**Comment by aditya98ak** [comment]
@accakks Okay, I'll share a doc for the course(s) and one 1-1.5 hour lecture for Python introduction.
